version: "3"

services:
    neo4j:
        image: neo4j:4.3.2-enterprise
        ports:
            - 7474
            - 7687
        volumes:
            - "neo4j-data:/data"
        environment:
            - NEO4J_AUTH=neo4j/neo4jSecret
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
            - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
            - NEO4J_dbms_memory_heap_initial__size=${NEO4J_dbms_memory_heap_initial__size:-4600m}
            - NEO4J_dbms_memory_heap_max__size=${NEO4J_dbms_memory_heap_max__size:-4600m}
            - NEO4J_dbms_memory_pagecache_size=${NEO4J_dbms_memory_pagecache_size:-1g}

volumes:
    neo4j-data:
